name: Docker Image Build

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: docker login ghcr.io --username AleksandrZhukovin --password ${{ secrets.PASSWORD }}
      - name: Build container
        run: docker build -t ghcr.io/aleksandrzhukovin/lab5 -f lab5/Dockerfile .
      - name: Push container
        run: docker push ghcr.io/aleksandrzhukovin/lab5
      - name: Run the container
        run: docker run --memory 4g --name ghcr.io/aleksandrzhukovin/lab5_container ghcr.io/aleksandrzhukovin/lab5